//
// Created by eu034534 on 12/21/2023.
//

#ifndef GRAPH_PUZZLE_GAME_HIDAYETERENULUDAG_MAIN_H
#define GRAPH_PUZZLE_GAME_HIDAYETERENULUDAG_MAIN_H


class main {

};


#endif //GRAPH_PUZZLE_GAME_HIDAYETERENULUDAG_MAIN_H
